### ISSUE TITLE
Enabled modules and blocks not properly stored

### ISSUE THREAD

**Issue by ewallah** [ffhs/moodle-block_course_checker#35] opened 2020-05-13 11:54 UTC
## Summary
The course checker does not store all settings:  which modules and blocks are enabled is not stored as it should. 

To reproduce, add the block admin_bookmarks and try to bookmark an admin page, one should not be redirected to a configuration of the course checker settings page.

Behat can also be used to reproduce this behavior:
`php admin/tool/behat/cli/run.php -vvv --colors --tags="@block_admin_bookmarks"`

### Actual result
3 scenarios (1 passed, 2 failed)
28 steps (21 passed, 2 failed, 5 skipped)
### Expected result
3 scenarios (3 passed)
28 steps (23 passed, 5 skipped)
### Appendix```

 RUN  Behat features for block_admin_bookmarks
Running single behat site:
Moodle 3.8.3+ (Build: 20200512), 9b2253898a16cb23590f02aae615a6519f9254b8
Php: 7.3.17.1.18.04.1.1, pgsql: 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1), OS: Linux 4.15.0-99-generic x86_64
Server OS "Linux", Browser: "firefox"
Browser specific fixes have been applied. See http://docs.moodle.org/dev/Acceptance_testing#Browser_specific_fixes
Started at 13-05-2020, 19:08
...............F-......F----

--- Failed steps:

001 Scenario: Admin page can be accessed through bookmarks block               # blocks/admin_bookmarks/tests/behat/bookmark_admin_pages.feature:22
      And I click on "Scheduled tasks" "link" in the "Admin bookmarks" "block" # blocks/admin_bookmarks/tests/behat/bookmark_admin_pages.feature:25
        Block matching locator "'Admin bookmarks'" not found.

        +--[ HTTP/1.1 200 | http://127.0.0.1:8000/admin/upgradesettings.php | GoutteDriver ]
        |
        |  <!DOCTYPE html>
        |
        |  <html  dir="ltr" lang="en" xml:lang="en">
        |  <head>
        |      <title>Acceptance test site: Administration: New settings</title>
        |      <link rel="shortcut icon" href="http://127.0.0.1:8000/theme/image.php/boost/theme/1589304451/favicon" />
        |      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        |  <meta name="keywords" content="moodle, Acceptance test site: Administration: New settings" />
        |  <link rel="stylesheet" type="text/css" href="http://127.0.0.1:8000/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.css" /><script id="firstthemesheet" type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script><link rel="stylesheet" type="text/css" href="http://127.0.0.1:8000/theme/styles.php/boost/1589304451_1/all" />
        |  <script>
        |  //<![CDATA[
        |  var M = {}; M.yui = {};
        |  M.pageloadstarttime = new Date();
        |  M.cfg = {"wwwroot":"http:\/\/127.0.0.1:8000","sesskey":"Tj6oxtn055","sessiontimeout":"7200","themerev":"1589304451","slasharguments":1,"theme":...
        |

002 Scenario: Admin page can be removed from bookmarks                         # blocks/admin_bookmarks/tests/behat/bookmark_admin_pages.feature:29
      And I click on "Scheduled tasks" "link" in the "Admin bookmarks" "block" # blocks/admin_bookmarks/tests/behat/bookmark_admin_pages.feature:32
        Block matching locator "'Admin bookmarks'" not found.

        +--[ HTTP/1.1 200 | http://127.0.0.1:8000/admin/upgradesettings.php | GoutteDriver ]
        |
        |  <!DOCTYPE html>
        |
        |  <html  dir="ltr" lang="en" xml:lang="en">
        |  <head>
        |      <title>Acceptance test site: Administration: New settings</title>
        |      <link rel="shortcut icon" href="http://127.0.0.1:8000/theme/image.php/boost/theme/1589304451/favicon" />
        |      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        |  <meta name="keywords" content="moodle, Acceptance test site: Administration: New settings" />
        |  <link rel="stylesheet" type="text/css" href="http://127.0.0.1:8000/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.css" /><script id="firstthemesheet" type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script><link rel="stylesheet" type="text/css" href="http://127.0.0.1:8000/theme/styles.php/boost/1589304451_1/all" />
        |  <script>
        |  //<![CDATA[
        |  var M = {}; M.yui = {};
        |  M.pageloadstarttime = new Date();
        |  M.cfg = {"wwwroot":"http:\/\/127.0.0.1:8000","sesskey":"yFQ2dBb85Q","sessiontimeout":"7200","themerev":"1589304451","slasharguments":1,"theme":...
        |

3 scenarios (1 passed, 2 failed)
28 steps (21 passed, 2 failed, 5 skipped)
0m13.43s (49.04Mb)
```

The error output is simple:
The settings shown below were added during your last Moodle upgrade. Make any changes necessary to the defaults and then click the 'Save changes' button at the bottom of this page.
New settings - Course checker
   Enabled modules
     Database 
     Forum
     Glossary
     Wiki
     Define the allowed modules
   Enabled blocks
    ....
     Define the allowed blocks 
Save changes

**Comment by adpe** [comment] 2020-05-13 12:49
Hi @ewallah 

Thanks for your issue.

I don't understand exactly what will break on `Behat` scenarios of that "core block plugin", because of our plugin.

Step by step what I've done:
1. Go to a course and click **Turn editing on**
2. Add a block **Admin bookmarks** and other blocks if desired
3. Go to **Course checker** plugin settings in `Site administration / Plugins`
4. Set **referencecourseid** to the course you added the block
5. Enable **checker_blocks_status** and at least `Admin bookmarks` in **blocks**
6. **Save settings** on bottom of the page
7. Open a different course and click **Turn editing on**
8. Add a block **Course checker**
9. Click **Check this course** button
10. Run cron manually (https://FQDN/admin/cron.php) or wait if it's configured to run in background oder CLI
11. Click on **View the detailed results**
![image](https://user-images.githubusercontent.com/9467708/81814319-f03d4880-9528-11ea-9c22-ad9d6a54406d.png)

HTH,
Adrian

**Comment by ewallah** [comment] 2020-05-13 15:27
Hi Adrian,

The problem is not about the use of the plugin:  the block works fine in a course with and without an admin bookmarks block. It works like it should, over here no complaints at all about the functionality.

But sometimes I am referred to the settings page of the course_checker block asking me for extra configuration on userdata_modules - activedates_modules - blocks:

The settings shown below were added during your last Moodle upgrade. 
Make any changes necessary to the defaults and then click the 'Save changes' button at the bottom of this page.
New settings - Course checker
![png](https://user-images.githubusercontent.com/1324161/81832495-db6baf80-953e-11ea-89df-628648d19beb.png)

When I first installed the plugin, I already saved my preferences, All changes about users - quiz - references - ... were stored correctly, so the settings page is asking me only for the missing settings: userdata_modules, activedates_modules and blocks of the course checker plugin.

If I check a least 1 userdata_module, the New settings - Course checker asks me in the future only about configuring activedates_modules and blocks, the userdata_modules settings disappeared. So the value is stored when 1 item is checked, but not when the default is used.

So, or the user should be unable to opt for 'none' - or this 'none' should be stored. 

R

**Comment by adpe** [comment] 2020-05-14 10:03
Okay - thanks for the further information @ewallah.

As I know, this is the Moodle default behavior. Moodle stores information where nothing is selected and the default value is set as `None` as a `empty` `mdl_config_plugin` setting (name => value).

```sql
MariaDB [moodle]> SELECT * FROM mdl_config_plugins WHERE name LIKE '%_modules' or name = 'blocks';
+------+----------------------+---------------------+-------+
| id   | plugin               | name                | value |
+------+----------------------+---------------------+-------+
| 2007 | block_course_checker | activedates_modules |       |
| 2010 | block_course_checker | blocks              |       |
| 2029 | block_course_checker | userdata_modules    |       |
+------+----------------------+---------------------+-------+
3 rows in set (0.01 sec)
```

Step-by-step:
1. Setup or use an existing Moodle **3.8** environment
2. Install this plugin with release **v3.8-r1** (`git checkout tags/v3.8-r1`)
3. **Skip** settings and leave defaults in (`upgradesettings.php`)
4. Click on **Save changes** on bottom of the page
5. Checkout new release **v3.8-r2** (`git checkout tags/v3.8-r2`)
6. Visit admin notifications page (Click on `Site administration`)
7. After upgrade, I was not asked to set new default settings.

And `activatedates_modules`, `userdata_modules` and `blocks` were set `empty` (check out **configlog** with `Site administration / Reports / Config changes`)

![image](https://user-images.githubusercontent.com/9467708/81921112-664db800-95da-11ea-86cc-9fb1ed810655.png)

I'm sorry but I can't follow your problem and I can't reproduce your behavior. Therefore, I'll close this issue.

HTH,
Adrian

**Closed as completed by adpe** 2020-05-14 10:03 UTC
Labels: documentation, enhancement

**Comment by ewallah** [comment] 2020-05-15 14:17
Step-by-step to reproduce the error:

1. Setup a new Moodle 3.8 environment
2. Install this plugin
3. Configure Behat
4. Run: php admin/tool/behat/cli/run.php -vvv --colors --tags="@block_admin_bookmarks"
5. Assure no errors are shown and no default course_checker values were asked.

[Same failure on travis.](https://travis-ci.org/github/ewallah/moodle-block_course_checker/jobs/687412913#L819)
[Other plugin to show this is not standard behaviour](https://travis-ci.org/github/ewallah/moodle-availability_coursecompleted/jobs/687389159#L472)

To check that this plugin is Behat compatible I added a [basic Behat script](https://github.com/ewallah/moodle-block_course_checker/blob/master/tests/behat/course_checker.feature):

```
@block @block_course_checker @javascript
Feature: Enable block course checker in a course
  In order to enable the course checker block in a course
  As a manager
  I can add course checker block to a course

  Background:
    Given the following "users" exist:
      | username | firstname | lastname | email           |
      | user     | User      | One      | one@example.com |
      | manager  | Max       | Manager  | man@example.com |
    And the following "role assigns" exist:
      | user    | role           | contextlevel | reference |
      | manager | manager        | System       |           |
    And the following "courses" exist:
      | fullname | shortname |
      | Course 1 | C1        |
    And the following "course enrolments" exist:
      | user     | course | role    |
      | manager  | C1     | manager |
      | user1    | C1     | student |

  Scenario: Create a new private template.
    Given I log in as "manager"
    And I am on "Course 1" course homepage with editing mode on
    And I add the "Course checker" block
    Then I should see "Last automatic check" in the "Course checker" "block"
```
This basic test should pass, but locally and on Travis, this [Behat](https://docs.moodle.org/dev/Behat_integration) script also fails.

**Comment by adpe** [comment] 2020-05-16 11:41
Hi @ewallah 

Thanks for reaching out with your Behat test. As you have seen, our plugin doesn't support Behat. And if I understand it correctly it should not lead to problems in Moodle core with the `admin_bookmarks` scenarios. They are independent.

What you're achieving was not working in due of an error in method `user_has_role_in_course` in `locallib.php`. I've seen that in your repo and figured that out. Further I've written a slightly different Behat testing scenario than yours.

Further your `.travis.yml` doesn't seem correct at all.

Check out all results on my private repo under https://github.com/adpe/moodle-block_course_checker and https://travis-ci.org/github/adpe/moodle-block_course_checker.

I'll check that when I'm back at work, if we want to official support Behat test scenarios. Actually we don't write these acceptance testing scenarios.

HTH,
Adrian

PS: I'll let this issue closed, as the values of the checkers are stored correctly. The other stuff discussed here later, has nothing to do with this issue.

**Comment by ewallah** [comment] 2020-05-19 18:07
Hi Adrian,

I see great potential in your plugin, hence my persistence.

There is 1 line in your code that reveals a lot: "We provide a fake settingpage so each checker can use it to add his own settings."   Perhaps this fake settingpage works fine to configure your plugin, but we know that at least the blocks/[admin_bookmarks](https://travis-ci.org/github/ewallah/moodle-block_course_checker/jobs/687794030#L717) is not happy with this fake.  To show the error I added the --dump parameter to the Travis job.

I can only advise that you get rid of this fake page in the future. 

R
