### ISSUE TITLE
Hardcoded strings, translation problems and resolution links

### ISSUE THREAD

**Issue by dinism** [ffhs/moodle-block_course_checker#33] opened 2020-05-07 08:52 UTC
Thanks for the plugin!
I'm a pt-pt translator.
Some strings are hardcoded in english (can't be translated)
### **No date found.**
![imagem](https://user-images.githubusercontent.com/14828021/81272356-49970a80-9045-11ea-8a55-27097f7e5c51.png)

### **Links check**
![imagem](https://user-images.githubusercontent.com/14828021/81272505-7b0fd600-9045-11ea-90ce-125b0c41b1b9.png)

**### Incorrect link to resolve**
![imagem](https://user-images.githubusercontent.com/14828021/81272288-31bf8680-9045-11ea-9ecb-7de95dfb3ae6.png)

### **STRANGE:**
![imagem](https://user-images.githubusercontent.com/14828021/81274432-2cb00680-9048-11ea-8907-fd113ac04dde.png)

**Comment by moleculech** [comment] 2020-05-07 09:34
Hi @dinism 

Thanks for pointing out the isssues and translating the plugin.

1. We check about the hardcoded language strings.

2. Link to resolve
What release and moodle version do you use?

3. Strange
We can fix that to

**Comment by dinism** [comment] 2020-05-07 11:43
>     1. We check about the hardcoded language strings.
Don't forget **Links check**
![imagem](https://user-images.githubusercontent.com/14828021/81290401-e9fa2880-905f-11ea-87e7-3ba795821bee.png)

>     2. Link to resolve
![imagem](https://user-images.githubusercontent.com/14828021/81290622-4bba9280-9060-11ea-8d9e-04d005c100bc.png)

**Comment by adpe** [comment] 2020-05-07 12:04
Hi @dinism 

Here a quick update.

#### Hardcoded strings
- [x] No date found *(Resolved with 99db292 - but pay attention, it will be included in the **next release***)
- [x] Links check *(Seems something related with AMOS, the string is not hardcoded)*

#### Links to resolve
- [x] First image *(It looks like you have moodle running on URL with path https://www.escolaagricolavendasnovas.com/moodle2/)*
- [x] Second image *(It looks like you have a second moodle (productive) running on URL with path https://www.escolaagricolavendasnovas.com/moodle/)*

At the moment we didn't verify that and it can be related to that. As you see pointed out right on your second image the `/moodle/` or `/moodle2/` is missing. Does the two images are from the same instance and the same plugin version? Because `modedit.php` isn't existing anymore and you should re-run the `checker_link` to crawl the activities again, as here were changes made.

Did you have the plugin installed before on an older version? I think so, when I see your images because of the paths.

#### Strange
- [x] New string were added and some old updated *(Could also be related to AMOS)*

Please check the new strings in this repo and not AMOS - some strings seems to miss there!. The `...google.com...` is old and should not be visible anymore...

I'm in contact with the AMOS maintainer of Moodle HQ.

HTH,
Adrian

**Comment by dinism** [comment] 2020-05-07 14:24
Hi

Thanks for you answer.
The **links check** string is in plugin directory/lang/eng/block_course_checker.php but it's not in AMOS
![imagem](https://user-images.githubusercontent.com/14828021/81304641-3b60e280-9075-11ea-8c8e-9560a8a11fd6.png)
**Links to resolve**
I have 2 moodle installations (moodle2 is for testing) and i only have the plugin installed in moodle2. ALL images are from the moodle2.
It first installed old version because i didn't change the version of the site from 3.7 to 3.8 in https://moodle.org/plugins/report/index.php?report=user_sites
**The steps was:**
![imagem](https://user-images.githubusercontent.com/14828021/81305072-cf32ae80-9075-11ea-879a-5ca48078a5f9.png)
![imagem](https://user-images.githubusercontent.com/14828021/81305110-d9ed4380-9075-11ea-88ae-1b8ba64514d2.png)
**Then i updated to 3.8-r1**
![imagem](https://user-images.githubusercontent.com/14828021/81305199-f5f0e500-9075-11ea-8882-0ba0797b9516.png)

Must i uninstall the plugin, download last version zip
![imagem](https://user-images.githubusercontent.com/14828021/81305551-5f70f380-9076-11ea-8b23-81ad567349bf.png)
and upload to my Moodle and install it from there?

**Comment by dinism** [comment] 2020-05-07 15:04
When i run cron.php manually i got:
![imagem](https://user-images.githubusercontent.com/14828021/81310670-4ff4a900-907c-11ea-956a-2ca6c77a407d.png)
or
![imagem](https://user-images.githubusercontent.com/14828021/81310701-58e57a80-907c-11ea-9ead-67fc94ea2237.png)

**Comment by adpe** [comment] 2020-05-08 12:51
Hi @dinism 

Can you please upgrade to the newest version (just released) and verify if the `string` problems were solved? Thanks again for updating the "new renamed" strings in AMOS.

And please check again, the last `strange` problem in due of the `resolution link`.

Thanks,
Adrian

**Comment by dinism** [comment] 2020-05-08 18:35
Hi

I uninstalled the plugin. I ran cron.ph through the browser: ... / admin / cron.ph. Everything went well.
 
![imagem](https://user-images.githubusercontent.com/14828021/81423528-76821500-914c-11ea-8d91-0b816d223fbb.png)

After I installed the 3.8-r2 version in a 3.8.2 Moodle. Clean installation. No need updates.
I ran the cron again and got this error:

![imagem](https://user-images.githubusercontent.com/14828021/81424047-396a5280-914d-11ea-8ba6-673683b1652e.png)
If i can´t run cron so i can't view the checker results

After I uninstalled the plugin. Installed version 3.6 r5. Didn't update
![imagem](https://user-images.githubusercontent.com/14828021/81431426-05952a00-9159-11ea-8255-128d332bf778.png)

I ran the cron and everything is OK. Take a look at the SPACE message.
![imagem](https://user-images.githubusercontent.com/14828021/81431668-6de40b80-9159-11ea-871f-2fffdbde811b.png)

After I uninstalled the plugin. Installed version 3.7 r3. Didn't update
![imagem](https://user-images.githubusercontent.com/14828021/81431969-fa8ec980-9159-11ea-8480-e70cba5c135a.png)

I ran the cron and everything is OK. But LINK to solve is wrong. Missing Moodle directory.
![imagem](https://user-images.githubusercontent.com/14828021/81432292-94ef0d00-915a-11ea-847c-3b117eec0358.png)

After i updated to version 3.8 r2. I didn´t ran the cron and i could see the results.
I ran the cron 3 times via browser and it worked. **The link to solve is not working. Missing the directory ..../moodle2/....**
After i added the plugin to another course. I ran and i got again an error
![imagem](https://user-images.githubusercontent.com/14828021/81437391-ffa44680-9162-11ea-9440-68f5c42c9f8c.png)

Any help?

**Comment by adpe** [comment] 2020-05-10 16:17
Hi @dinism 

You provided too much information and I can not follow all steps you have made. And also pay attention, that we don't support the `MOODLE_36_STABLE` branch anymore. The spacing was fixed in recent versions.

And to know why the adhoc task is failing, we need to know which checkers you have enabled and how these are configured. As we support many modules and blocks and various checkers, the error can be thrown from a lot of stuff. Maybe enable debugging would also help to get more detailed information.

Can we please just concentrate on the problem with the missing `moodle2` directory? The other stuff you reported should be fixed, right

Thanks and greets,
Adrian

**Comment by dinism** [comment] 2020-05-10 19:17
**My 2 moodle instalations are version 3.8, not 3.6 or 3.7. Just forgot to change it in MY SITES.
As i said the problem is with cron. Moodle2 is 3.8.1 When i intalled OLD version of plugin was to try understand what was wrong.
Today i tried again a clean installation. These were the steps i did:**
### **Before install the plugin, i ran the cron. Cron script completed correctly.**
![imagem](https://user-images.githubusercontent.com/14828021/81507137-21343800-92f3-11ea-812c-ab43a6c7faca.png)
### **My moodle2 is:**
![imagem](https://user-images.githubusercontent.com/14828021/81508024-580d4c80-92f9-11ea-85eb-0ba1fa19c062.png)
### **Then i installed the plugin**
![imagem](https://user-images.githubusercontent.com/14828021/81507240-e41c7580-92f3-11ea-961f-d0c11a8d43c2.png)
### **I didn't changed anything of settings**
![imagem](https://user-images.githubusercontent.com/14828021/81507326-84729a00-92f4-11ea-8d31-538f3a8bcb3e.png)
### **Then i added it to a course.**
![imagem](https://user-images.githubusercontent.com/14828021/81507638-aa00a300-92f6-11ea-864c-73b07d6653b2.png)
### **After i ran cron script via browser. I got this error in cron**
![imagem](https://user-images.githubusercontent.com/14828021/81507502-c5b77980-92f5-11ea-99d9-16b3f038d15b.png)
### **Then i came back to course and clicked in View detailed results**
![imagem](https://user-images.githubusercontent.com/14828021/81507759-5a6ea700-92f7-11ea-901d-5c4171e42dbe.png)
### **Then i waited for a automatic cron execution (each hour)**
![imagem](https://user-images.githubusercontent.com/14828021/81508068-9c005180-92f9-11ea-8c17-6b82959edf4c.png)
### **With this version i can't see detailed results because plugin don't let cron finish correctly and it takes a long time (more than 200 seconds)**
### **After i clicked in manual check and i got this:**
![imagem](https://user-images.githubusercontent.com/14828021/81508241-f2ba5b00-92fa-11ea-9681-bdbae771ae18.png)
### **I only see the detailed results if i install a old version, run cron and then update to 3.8-r2 and it keep working. But if i run cron via browser or automatic it gives error in cron execution and it will never update the results.**

**Comment by dinism** [comment] 2020-05-10 22:43
![imagem](https://user-images.githubusercontent.com/14828021/81512348-e42e6c80-9317-11ea-888b-75985efbbfa0.png)
![imagem](https://user-images.githubusercontent.com/14828021/81512323-c234ea00-9317-11ea-9411-5cd872a6ab1b.png)

**Comment by adpe** [comment] 2020-05-13 09:01
Hi @dinism 

I'm sorry but I can't reproduce your errors. What is your information about PHP, OS, MySQL? And do you have a clean installation made of your Moodle environment?

I just figured out the "issue" #34 and that's all. And first I installed the Course checker v3.8-r1, running the checker and then `cron`. And afterwards I upgraded the plugin and I got the same results (mentioned in #34).

We can not give you more support. And as we can't reproduce your behavior it's hard to investigate.

Greets,
Adrian

**Comment by dinism** [comment] 2020-05-13 13:34
![imagem](https://user-images.githubusercontent.com/14828021/81819141-d4d13e00-9526-11ea-9e75-aa745be59cb6.png)

**Comment by adpe** [comment] 2020-05-14 09:43
Thanks for the information @dinism . I've made that step-by-step as you can see in #34 and I was not able to reproduce your issue on a `clean Moodle 3.8.2 environment`. 

**Info**: The latest plugin version is not officially supporting PHP 7.1.

Feel free to open a new issue. Only with the information to reproduce the issue (according #34). Please don't paste too many images as it's hard to read out the relevant information and the issue will be too huge to follow.

Thank you for your understanding,
Adrian

**Closed as completed by adpe** 2020-05-14 09:43 UTC
Labels: bug, documentation
